version: '3.6'
services:

  # PostgreSQL
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  # Backend
  backend:
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/src/backend
    command: npm start
    working_dir: /usr/src/backend
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URI: postgres://admin:password@postgres:5432/smart-brain
      REDIS_URI: redis://redis:6379
  